# Development setup with backend and frontend running locally
# This file only runs the SQL Server database in Docker

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: ialign-sqlserver
    environment:
      SA_PASSWORD: "iAlign@2024!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - sqldata:/var/opt/mssql
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "iAlign@2024!" -Q "SELECT 1" || exit 1
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s

volumes:
  sqldata:
    driver: local
